[project]
name = "asr-evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jiwer>=4.0.0",
    "matplotlib>=3.10.6",
    "openai-whisper>=20250625",
    "pandas>=2.3.2",
    "streamlit>=1.49.1",
]
